# Generated by Django 4.2.7 on 2023-12-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_acessrecord_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topicname',
            new_name='topic_name',
        ),
        migrations.AddField(
            model_name='webpage',
            name='Email',
            field=models.EmailField(default='indian143@gmail', max_length=254),
        ),
    ]
