# Generated by Django 4.2.7 on 2023-12-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_webpage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='topicname',
            new_name='topic_name',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='Email',
            field=models.EmailField(default='indian143@gmail.com', max_length=254),
        ),
    ]
